// QUAN-20260530-2301
// This is a placeholder for the actual migration file.
// Generating the full migration code here is not feasible or practical in this format.
// The migration would typically be generated by running `dotnet ef migrations add AddStudentManagement`
// after all entities and configurations are set up.

// It should create the 'lops', 'trang_thai_hoc_sinh', and 'students' tables
// and include the seed data defined in LopConfiguration and TrangThaiHocSinhConfiguration.

// Example structure:

/*
using Microsoft.EntityFrameworkCore.Migrations;
using System;

#nullable disable

namespace ONENET.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddStudentManagement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "lops",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    ten_lop = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    mo_ta = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    created_by = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    updated_by = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_lops", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "trang_thai_hoc_sinh",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    ma_trang_thai = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    ten_trang_thai = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    mo_ta = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    created_by = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    updated_by = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_trang_thai_hoc_sinh", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "students",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    ma_hoc_sinh = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    ho_va_ten = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    ngay_sinh = table.Column<DateOnly>(type: "date", nullable: false), // Note: EF Core might generate DateOnly or DateTime.
                    gioi_tinh = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    dia_chi = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    sdt_phu_huynh = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    email_phu_huynh = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    lop_id = table.Column<Guid>(type: "uuid", nullable: false),
                    ngay_nhap_hoc = table.Column<DateOnly>(type: "date", nullable: false), // Note: EF Core might generate DateOnly or DateTime.
                    trang_thai_id = table.Column<Guid>(type: "uuid", nullable: false),
                    row_version = table.Column<uint>(type: "xid", rowVersion: true, nullable: false), // xmin column, EF Core maps to uint
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    created_by = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    updated_by = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_students", x => x.id);
                    table.ForeignKey(
                        name: "FK_students_lops_lop_id",
                        column: x => x.lop_id,
                        principalTable: "lops",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_students_trang_thai_hoc_sinh_trang_thai_id",
                        column: x => x.trang_thai_id,
                        principalTable: "trang_thai_hoc_sinh",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "lops",
                columns: new[] { "id", "created_at", "created_by", "is_deleted", "mo_ta", "ten_lop", "updated_at", "updated_by" },
                values: new object[,]
                {
                    { "01b1e2c3-d4e5-6f7a-8b9c-0d1e2f3a4b5d", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "Lớp 10 Ban A1", "10A1", null, null },
                    { "02b1e2c3-d4e5-6f7a-8b9c-0d1e2f3a4b5d", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "Lớp 10 Ban A2", "10A2", null, null },
                    { "03b1e2c3-d4e5-6f7a-8b9c-0d1e2f3a4b5d", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "Lớp 11 Ban B1", "11B1", null, null },
                    { "04b1e2c3-d4e5-6f7a-8b9c-0d1e2f3a4b5d", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "Lớp 12 Ban C", "12C", null, null }
                });

            migrationBuilder.InsertData(
                table: "trang_thai_hoc_sinh",
                columns: new[] { "id", "created_at", "created_by", "is_deleted", "ma_trang_thai", "mo_ta", "ten_trang_thai", "updated_at", "updated_by" },
                values: new object[,]
                {
                    { "0a1b2c3d-e4f5-6a7b-8c9d-0e1f2a3b4c5e", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "DANG_HOC", "Học sinh đang theo học tại trường.", "Đang học", null, null },
                    { "1a1b2c3d-e4f5-6a7b-8c9d-0e1f2a3b4c5e", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "DA_TOT_NGHIEP", "Học sinh đã hoàn thành chương trình học và tốt nghiệp.", "Đã tốt nghiệp", null, null },
                    { "2a1b2c3d-e4f5-6a7b-8c9d-0e1f2a3b4c5e", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "DA_CHUYEN_TRUONG", "Học sinh đã chuyển sang trường khác.", "Đã chuyển trường", null, null },
                    { "3a1b2c3d-e4f5-6a7b-8c9d-0e1f2a3b4c5e", new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc), "system_seed", false, "TAM_DUNG", "Học sinh tạm thời dừng việc học.", "Tạm dừng", null, null }
                });

            migrationBuilder.CreateIndex(
                name: "IX_lops_ten_lop",
                table: "lops",
                column: "ten_lop",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_students_ho_va_ten",
                table: "students",
                column: "ho_va_ten");

            migrationBuilder.CreateIndex(
                name: "IX_students_lop_id",
                table: "students",
                column: "lop_id");

            migrationBuilder.CreateIndex(
                name: "IX_students_ma_hoc_sinh",
                table: "students",
                column: "ma_hoc_sinh",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_students_trang_thai_id",
                table: "students",
                column: "trang_thai_id");

            migrationBuilder.CreateIndex(
                name: "IX_trang_thai_hoc_sinh_ma_trang_thai",
                table: "trang_thai_hoc_sinh",
                column: "ma_trang_thai",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "students");

            migrationBuilder.DropTable(
                name: "lops");

            migrationBuilder.DropTable(
                name: "trang_thai_hoc_sinh");
        }
    }
}
*/
// The actual timestamp in the filename will be `YYYYMMDDHHmmss_AddStudentManagement.cs`
// based on when `dotnet ef migrations add` command is executed.
// The content inside the `Up` and `Down` methods would be auto-generated by EF Core.
// I have provided the intended structure and content for clarity.